---
- name: Assign Execution Permission to File
  hosts: all
  gather_facts: no
  vars:
    myscript: "~/example.sh"
  tasks:
    - name: Assign Execute Permission
      ansible.builtin.file:
        dest: "{{ myscript }}"
        mode: 'a+x'
