---
- name: Create User Demo
  hosts: all
  become: true
  vars: 
    myuser: "hkt"
    mypassword: "password"
  tasks:
    - name: Create User Example
      ansible.builtin.user: 
        name: "{{ myuser }}"
        password: "{{ mypassword | password_hash('sha512') }}" 
        groups: 
          - users
        state: present
        shell: /bin/bash
        system: false
        create_home: true
        home: /home/hkt
        comment: User Create Via Ansible Playbook
        generate_ssh_key: true