---
- name: Cron Demo
  hosts: all
  tasks:
    - name: Cron Job Demo
      ansible.builtin.cron:
        name: "test"
        state: present
        minute: "*/2"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        job: 'logger "ansible-course"'