---
- name: Run Command on Local Host
  hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    - name: Print hostname
      debug:  
        msg: "{{ inventory_hostname }}"  