---
- name: Reboot Demo 
  hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Reboot VM Using Ansible Module
      ansible.builtin.reboot:
        msg: "Reboot by Ansible"
        pre_reboot_delay: 5
        post_reboot_delay: 10
        test_command: whoami
