---
- name: Rename File 
  hosts: all
  vars:
    mysrc: "/opt/foo"
    mydest: "~/bar"
  tasks:
    - name: Check if file exists
      ansible.builtin.stat:
        path: "{{ mysrc }}"
      register: check_file_name

    - name: Print Existing File
      ansible.builtin.debug:
        var: check_file_name

    - name: Rename file using copy module
      ansible.builtin.copy:
        remote_src: true 
        src: "{{ mysrc }}"
        dest: "{{ mydest }}"
      when: check_file_name.stat.exists

    - name: Remove old file
      ansible.builtin.file:
        path: "{{ mysrc }}"
        state: absent
      when: check_file_name.stat.exists